[build]
  base = "packages/chisel-site"
  publish = "_site/"
  command = "pnpm build"
  ignore = "git diff --quiet HEAD^ HEAD packages/chisel-site/"
[build.environment]
  NPM_FLAGS="--prefix=//dev/null"